import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
// import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <nav>
          <Link href="/">홈</Link><br />
          <Link href="/product">상품</Link><br />
          <Link href="/login">로그인</Link><br />
          <Link href="/mypage">마이페이지</Link><br />
        </nav> <br />
        {children}
      </body>
    </html>
  );
}
