import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";


import Header from '@/components/Header'
import Footer from '@/components/Footer'
import ChatbotWindy from "@/components/ChatbotWindy";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const brandSerif = Playfair_Display({
  variable: "--font-brand-serif",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${brandSerif.variable} flex flex-col bg-white text-neutral-900`}
      >

        <Header />
        <main className="w-full"> {children} </main>
        <Footer />
        <ChatbotWindy />

      </body>
    </html>
  );
}
